### ISSUE TITLE
Add Seed Data for the Institution

### ISSUE THREAD

**Issue by chahmedejaz** [EduardoSimon/budget.io#36]
- Currently, we don't create any record for the `Institution` in the `seeds.rb` file and we are using it for the `Account` creation.
- Hence it gives the error during `rails db:seed`
- We need to create Inistition before  `Account` creation.

**Comment by chahmedejaz** [comment]
Hey @EduardoSimon - I did a bit of spike on this issue and turns out I missed this file:
https://github.com/EduardoSimon/budget.io/blob/160332e25f857464119ccb10f779cebff68ca6b3/db/migrate/20221229143942_add_institutions_from_open_banking_provider.rb#L1-L17

We are creating the institutions in the migration file from the gocardless. This is the same issue I [discussed here](https://github.com/EduardoSimon/budget.io/issues/38#issuecomment-1764058940). 
But still there might be the case we don't get any institutions from the gocardless, then this issue will persist.

I think creating the institutions from the gocardless is not a good approach here.
We are doing an API call in middle of the migration, and due to invalid creds, this migration fails and the rest of the migrations don't get triggered.
I think in the places we are creating initial application data from the gocardless client, we should remove that and create that those  with hard-coded dummy data. 
What do you think about say?

**Comment by EduardoSimon** [comment]
Firstly, let me thank your for investing your time in helping the project. After that, let's get to the point. I completely understand your concern mainly because I had it myself too when developing the app. My idea was to be as lean as possible that's why I did not invest time in making the project more resilient to configuration issues. Having said that, it's true that the migration process should not request any data from gocardless as it makes them flaky, agreed. Nevertheless, we need the institution   data in order to support the authentication mechanism from gocardless. I initially thought that having the data already in the DB was going to be super comfortable to work with, but I think we can do better now.

I have a set of possible solutions in mind:
- As you mention, let's add some dummy data for local development to support an environment that does not have the API keys set up.
- On top of that, how about if we create a rake that allows to populate the institutions table with gocardless data, something like: `bundle exec rake sync_institution_data` and do basically the same thing as the migration does.


Moreover, we could make it even more resilient by adopting a lazy-loading strategy, which would load the institution data from GoCardless when necessary and cache it in the DB. However, I think its a bit over kill. I'm more keen on seeding mock data and having a rake to sync the data.

**Comment by chahmedejaz** [comment]
> Firstly, let me thank your for investing your time in helping the project. After that, let's get to the point. I completely understand your concern mainly because I had it myself too when developing the app. My idea was to be as lean as possible that's why I did not invest time in making the project more resilient to configuration issues. Having said that, it's true that the migration process should not request any data from gocardless as it makes them flaky, agreed. Nevertheless, we need the institution   data in order to support the authentication mechanism from gocardless. I initially thought that having the data already in the DB was going to be super comfortable to work with, but I think we can do better now.
> 
> I have a set of possible solutions in mind:
> - As you mention, let's add some dummy data for local development to support an environment that does not have the API keys set up.
> - On top of that, how about if we create a rake that allows to populate the institutions table with gocardless data, something like: `bundle exec rake sync_institution_data` and do basically the same thing as the migration does.
> 
> 
> Moreover, we could make it even more resilient by adopting a lazy-loading strategy, which would load the institution data from GoCardless when necessary and cache it in the DB. However, I think its a bit over kill. I'm more keen on seeding mock data and having a rake to sync the data.

It's a pleasure contributing to this project, @EduardoSimon. 😄
I totally agree with your solutions. That's exactly how we should handle this issue. Let me implement them and get back to you. :)

**Comment by EduardoSimon** [comment]
Thank you! Looking forward to it!

**Comment by chahmedejaz** [comment]
Hey @EduardoSimon - The fix for this issue has been submitted, would love to hear your thoughts on it. Thanks :)
